- name: Servers Management
  hosts: servers
  tasks:
    - name: Update and upgrade yum packages
      yum:
        name: '*'
        state: latest

    - name: Install webserver
      yum:
        name: httpd
        state: present

    - name: start the webserver
      service:
        name: httpd
        state: started 