- name: Docker Container Management
  hosts: servers
  tasks:
    - name: Update and upgrade yum packages
      yum:
        name: '*'
        state: latest

    - name: Install Python3
      yum:
        name: python3
        state: present

    - name: Install Docker
      yum:
        name: docker
        state: present
